import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={'bg-white p-4 shadow'}>
          <Link href={'/'} className={'p-2 hover:bg-blue-200'}>
            Home
          </Link>
          <Link href={'/other'} className={'p-2 hover:bg-blue-200'}>
            Other
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
